variables:
    MYSQL_DATABASE: manypizzas
    MYSQL_ROOT_PASSWORD: password

phpunit:
    stage: test
    image: php:7.0
    services:
        - mysql:5.7
    script:
        - bash .gitlab-ci.sh > /dev/null 2>&1
        - vendor/bin/phpunit --coverage-text --colors=never --coverage-html tests/_coverage/
        - vendor/bin/phpcs --standard=PSR2 app/
    artifacts:
        paths:
            - tests/_coverage
pages:
    stage: deploy
    dependencies:
        - phpunit
    script:
        - mv tests/_coverage/* public/
    artifacts:
        paths:
            - public
        expire_in: 30 days
    only:
        - master
