variables:
    MYSQL_DATABASE: manypizzas
    MYSQL_ROOT_PASSWORD: password

phpunit:
    stage: test
    image: php:7.0
    services:
        - mysql:5.7
    script:
        - bash .gitlab-ci.sh > /dev/null 2>&1
        - php vendor/bin/phpunit --coverage-text --coverage-html coverage
    artifacts:
        paths:
            - coverage

pages:
    stage: deploy
    dependencies:
        - phpunit
    script:
        - mv coverage/* public/
    artifacts:
        paths:
            - public
        expire_in: 30 days
    only:
        - master
