variables:
    MYSQL_DATABASE: manypizzas
    MYSQL_ROOT_PASSWORD: password

codeception:
    stage: test
    image: php:7.0
    services:
        - mysql:5.7
    script:
        - bash .gitlab-ci.sh > /dev/null 2>&1
        - php vendor/bin/codecept run --coverage --coverage-html
    artifacts:
        paths:
            - tests/_output/coverage

pages:
    stage: deploy
    image: ruby:2.3
    dependencies:
        - codeception
    script:
        - mv tests/_output/coverage/* public/
    artifacts:
        paths:
            - public
        expire_in: 30 days
    only:
        - master
