before_script:
  - bash .gitlab-ci.sh

variables:
  MYSQL_DATABASE: manypizzas
  MYSQL_ROOT_PASSWORD: password

phpunit:php7.0:mysql5.7:
  image: php:7.0
  services:
    - mysql:5.7
  script:
    - php vendor/bin/codecept run